[package]
name = "run_py_script_in_browser_with_wasm_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imagequant = { version = "4.0", default-features = false }
png = "0.17.10"
